version: '3.7'

services:
    nginx:
        image: nginx:latest
        container_name: nginx
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./data/nginx:/etc/nginx/conf.d
            - ./cosmos-snapshots:/root
            - ./logs/nginx:/var/log/nginx
            - ./nginx/error.log:/etc/nginx/error_log.log
            - ./nginx/cache/:/etc/nginx/cache
            - ./default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - nginx

networks:
    nginx:
        driver: bridge
