version: '3.7'

services:
    nginx:
        image: nginx:latest
        container_name: nginx
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./data/nginx:/etc/nginx/conf.d
            - ./cosmos-snapshots:/root
            - ./logs/nginx:/var/log/nginx
            - ./nginx/error.log:/etc/nginx/error_log.log
            - ./nginx/cache/:/etc/nginx/cache
            - ./default.conf:/etc/nginx/conf.d/default.conf
            - /etc/letsencrypt:/etc/letsencrypt
            - /var/www:/var/www/certbot
        #command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
        networks:
            - nginx
    
    certbot:
        image: certbot/certbot
        container_name: certbot
        restart: unless-stopped
        volumes:
            - /etc/letsencrypt:/etc/letsencrypt
            - /var/www:/var/www/certbot
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
        networks:
            - nginx

networks:
    nginx:
        driver: bridge
